### PR TITLE
Fix Megacloud extractVariables for Zoro

### LINKED ISSUE #517: ZORO fetchEpisodeSources() throws error
### Describe the bug

fetchEpisodeSources() method is returning following error 

### Steps to reproduce

Run the zoro test using jest.

Its only failing for `fetchEpisodeSources()` method

### Expected behavior

It should load episode sources.

### Actual behavior

Its Breaking while decrypting the contents.

### Additional context

Code block responsible from file `extractors/megacloud.ts`:
```ts
decrypt(encrypted: string, keyOrSecret: string, maybe_iv?: string) {
    let key;
    let iv;
    let contents;
    if (maybe_iv) {
      key = keyOrSecret;
      iv = maybe_iv;
      contents = encrypted;
    } else {
      const cypher = Buffer.from(encrypted, "base64");
      const salt = cypher.subarray(8, 16);
      const password = Buffer.concat([
        Buffer.from(keyOrSecret, "binary"),
        salt,
      ]);
      const md5Hashes = [];
      let digest = password;
      for (let i = 0; i < 3; i++) {
        md5Hashes[i] = crypto.createHash("md5").update(digest).digest();
        digest = Buffer.concat([md5Hashes[i], password]);
      }
      key = Buffer.concat([md5Hashes[0], md5Hashes[1]]);
      iv = md5Hashes[2];
      contents = cypher.subarray(16);
    }

    const decipher = crypto.createDecipheriv("aes-256-cbc", key, iv);
    const decrypted =
      decipher.update(
        contents as any,
        typeof contents === "string" ? "base64" : undefined,
        "utf8"
      ) + decipher.final();

    return decrypted;
  }
```
Error thrown while processing following line
```ts
decipher.final()
```

Error:
```
Error: error:1C80006B:Provider routines::wrong final block length
    at Decipheriv.final (node:internal/crypto/cipher:193:29)
```

Suggestions: I'm not aware of the encryption process but it seems like `contents` is of size `482` which is not a multiple of `16`. Not sure whether this will solve the issue or not.

CC: @riimuru @jasanpreetn9

### PR DESCRIPTION
**Pull request by Kylart**
**What kind of change does this PR introduce?**
It seems gogoanime are working on making this difficult or something.

This PR fixes (again) Megacloud extractVariables for Zoro.

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Other information**
Fixes #517

### CODE REVIEW

**Comment by Kylart** [comment]
I wanted to add built files but my `yarn build` made a ton of file changes even on unrelated files

**Comment by Kylart** [comment]
@abdelaziz-mahdy Can you confirm it's working with these changes?

**Comment by abdelaziz-mahdy** [comment]
> @abdelaziz-mahdy Can you confirm it's working with these changes? 

I am not sure if I was correctly mentioned here , since I am not the maintainer of the code 😅

**Comment by abhishek-exists** [comment]
Its not reliable @Kylart I used uptime kuma and it seems they change their js code regularly. 
I found the best regex which is still working for me even during different alterations
Let me know if you're still facing issues with it. 

```ts
allvars =
        text
          .match(/\w{1,2}=new URLSearchParams\(window\[.+?new MobileDetect.+?;(?=function)/gm)
          ?.at(-1) ?? "";
```

CC: @riimuru

**Comment by riimuru** [comment]
I just tested it, and it seems to be working fine

**Pull request merged**
