### PR TITLE
Some improvements on 9anime.ts

### PR DESCRIPTION
**Pull request by BiometricGlitch**
**What kind of change does this PR introduce?**

Some improvements on 9anime.ts, hypothetically faster now?

**Did you add tests for your changes?**

Im lazy :p

**If relevant, did you update the documentation?**

Im really lazy :p but atleast the 9anime.ts is faster now

**Summary**

Basically made some improvements on 9anime.ts, it is hypothetically faster now

**Other information**

Keep going Consumet :D

### CODE REVIEW

**Review by riimuru — CHANGES_REQUESTED** [review]
Can you remove the ‘domhandler’ library from package.json. And remove the other unnecessary replit files

**Comment by BiometricGlitch** [comment]
> Can you remove the ‘domhandler’ library from package.json. And remove the other unnecessary replit files

Alright

**Review by riimuru — CHANGES_REQUESTED** [review]
@BiometricGlitch can you remove the unnecessary replit files

**Comment by nine-anime** [comment]
@enimax-anime  
We don't like this, please stop to not waste your time.

**Comment by TDanks2000** [comment]
can you please explain the benefit of changing from .pl -> .to is?

**Pull request closed without merging**
