### PR TITLE
 fix(mixdrop): positive look-behind issue [iOS/Expo]

### PR DESCRIPTION
**Pull request by aidanjuma**
**What kind of change does this PR introduce?**
Fix for iOS/Expo when using consumet.ts library on the client side.

**Did you add tests for your changes?**
No; tested on https://regexr.com/ with multiple cases.

**If relevant, did you update the documentation?**
No need.

**Summary**
Positive look-behind regex breaks on iOS/Safari and Expo due to lack of support; @TDanks2000 and I worked out some fixes using other regular expressions to achieve the same result, so a big thanks to him!

### CODE REVIEW

**Comment by aidanjuma** [comment]
@riimuru if you could, would you be able to have a quick look at this? Thanks!

**Comment by aidanjuma** [comment]
This Regex pattern seems to appear across a multitude of the extractors as well as mixdrop.ts; I'll look into changing those, too?

**Comment by aidanjuma** [comment]
Note: Previous commit was labelled wrong and contained an incorrect fix (ebf7df9), so I have now force-pushed the correct fix ( 4c164ee). Thanks!

**Comment by riimuru** [comment]
LGTM 👍

**Review by riimuru — APPROVED** [review]

**Pull request merged**
