### PR TITLE
fix(streamwish): Grab video sources extractor

### PR DESCRIPTION
**Pull request by hase0278**
**What kind of change does this PR introduce?**

Bug fix for streamwish video grabber and add streamwish to gogoanime video streaming servers

**Summary**
This fixes streamwish video extractor. My motivation for this is that this will be used on gogoanime provider as alternative to gogocdn

### CODE REVIEW

**Review by riimuru — APPROVED** [review]

**Comment by riimuru** [comment]
@hase0278 I see you have added other new commits. Is it ready to merge now?

**Comment by hase0278** [comment]
> @hase0278 I see you have added other new commits. Is it ready to merge now?

Yes its ready now

**Comment by hase0278** [comment]
> @hase0278 I see you have added other new commits. Is it ready to merge now?

Yes its ready now @riimuru just minimized the 403 forbidden streams error but it is unavoidable at the moment.

**Review by riimuru — APPROVED** [review]

**Comment by hase0278** [comment]
Thanks @riimuru I'll look into it later.

**Comment by hase0278** [comment]
> @hase0278 the 403 errors are most likely happening because the request is not yet fully reciprocal to the one they make.

After months of looking out for the issue, seems like streamwish literally forbids known server IPs from getting their m3u8 stream thus it is throwing 403 forbidden while when used directly on client side, everything works fine.

**Pull request merged**
