### PR TITLE
9anime.js

### PR DESCRIPTION
**Pull request by azimkhan0**
**What kind of change does this PR introduce?** 9anime changed their domain to aniwave.to

 new provider, 

**Did you add tests for your changes?** yes

**If relevant, did you update the documentation?** yes

**Summary**

**Other information**

### CODE REVIEW

**Review by riimuru — COMMENTED** [review]
All provider code changes should be done under `src` directory.

**Comment by Lousrj** [comment]
> All provider code changes should be done under `src` directory.

Hey man, I am Suraj and I'm looking for someone to start an anime website with, This project is going to be for long run, so if you're interested lmk so we can talk further about this.

**Comment by zuhaz** [comment]
Hey Suraj, I'm interested in building this project with you. @realzuhaz is my discord, lmk!

**Comment by Lousrj** [comment]
> realzuhaz

I have sent a request to your discord, My name is  lou_srj on discord

**Pull request closed without merging**
