### PR TITLE
Fixes examples in docs

### PR DESCRIPTION
**Pull request by illusionTBA**
**What kind of change does this PR introduce?**
- Fixes code examples used in the docs

**If relevant, did you update the documentation?**
- **Yes**

**Summary**
- In short, all the code examples in the docs were missing a closing parenthesis to end the `.then` statement.

### CODE REVIEW

**Comment by riimuru** [comment]
@illusionTBA can you do the same thing for other providers

**Comment by illusionTBA** [comment]
Yea ill go ahead and do that

**Comment by illusionTBA** [comment]
i thought i already did all the providers, did i miss one ?

**Comment by riimuru** [comment]
@illusionTBA nvm i'm just tired 😅.

**Pull request merged**
