### PR TITLE
bugfix: extract url source at flixhq 

### LINKED ISSUE #569: Add Provider request
### Source name

AnimeSama

### Source link

https://animesama.biz/

### Language

french

### Source type

Anime

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by dhelbegor**
**What kind of change does this PR introduce?**
Solved a bug when trying to extract source url at flixHQ.

**Did you add tests for your changes?**
No, bug the tests related to the functionality is working now.

**If relevant, did you update the documentation?**
No

**Summary**
Closes #569

**Other information**

### CODE REVIEW

**Review by riimuru — APPROVED** [review]

**Comment by fsmdeveloper** [comment]
Thank you, brother! I am checking it.

**Comment by dhelbegor** [comment]
> Thank you, brother! I am checking it.

You are welcome. Please, let me know if it works correctly for you too :D.

**Comment by fsmdeveloper** [comment]
**YES BROTHER!!! 😍 It's working properly! thank you so much!! ❤️❤️

**Comment by fsmdeveloper** [comment]
**`movie/watch-avatar-19690`**

Bro, is there any way to retrieve TMDB ID or IMDb ID using the media ID? **`"19690"`**

**Comment by dhelbegor** [comment]
> **`movie/watch-avatar-19690`**
> 
> Bro, is there any way to retrieve TMDB ID or IMDb ID using the media ID? **`"19690"`**

hummm, I don't think so. they are diferent ID's. maybe u can use the movie/tv series title and retrieve the data from those sites.

you can try to bring the discussion to discord: https://discord.gg/dDmyZ9X3

**Comment by fsmdeveloper** [comment]
> > **`movie/watch-avatar-19690`**
> > Bro, is there any way to retrieve TMDB ID or IMDb ID using the media ID? **`"19690"`**
> 
> bro help me how to install the consumet.ts in server I have install npm but I cant run consumet.ts bro pleaseee. now I install only pull from docker from api.consumet.org please sahre to me step by step to run consumet.ts contact me on telegram t.me/kimjonghung

you can run consumet.ts. it's a standalone package. you should install it on you own nodejs project. or use api.consumet.org and deploy it directly on your vps or vercel.

**Comment by ClayArsenio26** [comment]
``> > > **`movie/watch-avatar-19690`**
> > > Bro, is there any way to retrieve TMDB ID or IMDb ID using the media ID? **`"19690"`**
> > 
> > 
> > bro help me how to install the consumet.ts in server I have install npm but I
> 
> I cant run consumet.ts bro pleaseee. now I install only pull from docker from api.consumet.org please sahre to me step by step to run consumet.ts contact me on telegram t.me/kimjonghung
> 
> [ClayArsenio26](https://github.com/ClayArsenio26)
> 
> **You can't run consumet.ts. it's a standalone package. you should install it on you own nodejs project. or use api.consumet.org and deploy it directly on your vps or vercel**
> 
> https://conmet.vercel.app/ use this

now I have deploy into my vps, but still not working. please tell me bro how to work it? 
in my file .mjs
`import { MOVIES } from "@consumet/extensions";

const goku = new MOVIES.FlixHQ();


const args = process.argv.slice(2);
const idepisode = args[0];
const mediainfo = args[1];


goku.fetchEpisodeSources(idepisode, mediainfo).then(data => {

  //const jsonData = JSON.stringify(data);
  console.log(jsonData);
})

`

and in my file .php
`<?php
header('Content-Type: application/json; charset=utf-8');
//$nama=$argv[$1];

$query1 = $_GET['query'];
//print_r($query1);
//$query2 = "query2 avenger";

$escapedQuery1 = escapeshellarg($query1);
//$escapedQuery2 = escapeshellarg($query2);

$output = shell_exec("/usr/bin/node goku_search.mjs $escapedQuery1");

//$output = shell_exec("/usr/bin/node goku.mjs 2>&1");

//echo '<pre>';
echo ($output);
//echo '</pre>';

//$nama='/www/wwwroot/direct-hls.acefile.eu.org/consumet/consumet2/batman.json';
//file_put_contents($nama,$output);
//echo $nama."\n";

`

**Comment by fsmdeveloper** [comment]
You need to build the consumet.ts (dist)

fork consumet.ts in your github account, then clone it on your desktop, then yarn install then yarn build

` "build": "rimraf dist && tsc -p tsconfig.json",`

**Comment by ClayArsenio26** [comment]
image
this is work well, but when I access from direct file php in browser its dont work, when execute on terminal its work well. can you help me bro ?

**Comment by fsmdeveloper** [comment]
> image this is work well, but when I access from direct file php in browser its dont work, when execute on terminal its work well. can you help me bro ?


I can't help with PHP! I wouldn't say I like this language. Seek help from a PHP expert

**Comment by ClayArsenio26** [comment]
> **YES BROTHER!!! 😍 It's working properly! thank you so much!! ❤️❤️ 

can u share how run methods ur code like that from url with parameters??

**Comment by fsmdeveloper** [comment]
> > **YES BROTHER!!! 😍 It's working properly! thank you so much!! ❤️❤️ 
> 
> can u share how run methods ur code like that from url with parameters??



share your Whatsapp number, I'll help you.

**Comment by gabinfinity** [comment]
Is it still working? It doesnt works for me

**Comment by ClayArsenio26** [comment]
> Is it still working? It doesnt works for me

work for me 
this info media api 
https://direct-hls.acefile.eu.org/consumet_new/consumet.ts/goku_mediainfo.php?mediainfo=movie/watch-avatar-19690

in my execute shell its work fine when I call from php its not work 
https://direct-hls.acefile.eu.org/consumet_new/consumet.ts/goku_source_q.php?idepisode=19690&mediainfo=movie/watch-avatar-19690

**Comment by fsmdeveloper** [comment]
Other endpoints work well, but the **`/watch`** (Streaming links) endpoint is not working again

**Comment by fsmdeveloper** [comment]
[dhelbegor](https://github.com/dhelbegor) brother can you check it?? it's the same issue again! 😒

**Pull request merged**
