### PR TITLE
Fixed gogoanime info endpoint

### PR DESCRIPTION
**Pull request by hasilon88**
**Bugfix**

**Tested and everything works except getting the episodes but that isn't available on the gogoanime website as well**

**Summary**

I am self hosting a API that uses this library and everything was fine until suddenly, the info endpoint kept returning a empty object. I looked around and modified the code a bit until I finally saw a error message that said that the website related to the  SSL certificate isn't correct and it gave me a list of URLs that were. I replaced the old `ajax`  #URL by the new recommended one and it starting working again.

The only issue still left is that the list of episodes is still empty but that is a issue directly from gogoanime. The reason I know this is because if you go on their website, you will see that the episodes lists never load so I believe once they fix that issue, the list of episode should work here as well.

2 users posted a issue about the exact same bug that this fixes: 
1. [First bug post related to the info endpoint from goganime](https://github.com/consumet/api.consumet.org/issues/574) 
2. [Second bug post related to the info endpoint from gogoanime](https://github.com/consumet/consumet.ts/issues/483)

I am sorry if this is not very clear, this is my first contribution ever. If you want to ask me anything, please don't hesitate.

### CODE REVIEW

**Comment by hasilon88** [comment]
Can someone explain to me what failed and what's the error please. I don't understand it.

**Comment by hase0278** [comment]
> Can someone explain to me what failed and what's the error please. I don't understand it.

You only changed js file? Not ts one?

**Comment by hasilon88** [comment]
yeah, since the ts file only contains signatures, i didn't need to modify the ts file

**Comment by dhelbegor** [comment]
Consumet were created using typescript. That file that u just modified is a builded file that was created by running npm run build. U need to modify the .ts one. And the .js files should not be versioned.

**Comment by hasilon88** [comment]
Which related ts file should i modify because the ones i see are all interfaces (method signatures)

**Comment by dhelbegor** [comment]
I think that is what u are looking for.

https://github.com/consumet/consumet.ts/blob/master/src%2Fproviders%2Fanime%2Fgogoanime.ts#L27

**Comment by hasilon88** [comment]
Oh thank you, I couldn't find it earlier, I'll try changing that instead.

**Comment by kurays015** [comment]
Suddenly, the meta/anilist endpoint is not working and the episodes is empty.

**Comment by dhelbegor** [comment]
> Oh thank you, I couldn't find it earlier, I'll try changing that instead.

Yw mate  :D

**Pull request closed without merging**
