### PR TITLE
refactor: refactor code at zoro

### PR DESCRIPTION
**Pull request by jasanpreetn9**
**What kind of change does this PR introduce?**
Refactor scrapeCard function at zoro.

**Did you add tests for your changes?**
I did not add tests.

**Summary**
Refactor scrapeCard function at zoro as then it can be reused.

### CODE REVIEW

**Review by riimuru — COMMENTED** [review]
You should be able to combine `scrapeCardPage` and `scrapeCard` under the function `scrapeCard` right?

**Comment by jasanpreetn9** [comment]
Yes, but this way scrapeCard can be reused for recommendations.

**Comment by riimuru** [comment]
@jasanpreetn9 which recommendations?

**Comment by jasanpreetn9** [comment]
Anime recommendations from fetchAnimeInfo.

**Pull request merged**
