### PR TITLE
Fixes for FlixHQ and ViewAsian

### PR DESCRIPTION
**Pull request by theonlymo**
Fixes for FlixHQ and ViewAsian

### CODE REVIEW

**Comment by OshekharO** [comment]
Have you also fixed cover image in recent?

**Review by riimuru — APPROVED** [review]

**Comment by OshekharO** [comment]
Also need to update keys for zoro provider

**Comment by theonlymo** [comment]
@OshekharO  
- can you point me what is the issue exactly with the recent? can we solve it in different PR? 
- zoro provider works fine with this. what do you mean?

**Comment by OshekharO** [comment]
> @OshekharO
> 
> * can you point me what is the issue exactly with the recent? can we solve it in different PR?
> * zoro provider works fine with this. what do you mean?

@theonlymo 

Yes, there is no recent or homepage in flixhq and from search cover is missing.

Also no recent is in viewasian.

**Pull request merged**
